CREATE TABLE advance_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    report_global_advance boolean,
    advance_type_id bigint
);


ALTER TABLE advance_assignment OWNER TO libreplan;

--
-- TOC entry 199 (class 1259 OID 1366675)
-- Name: advance_assignment_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE advance_assignment_template (
    id bigint NOT NULL,
    version bigint NOT NULL,
    advance_type_id bigint,
    order_element_template_id bigint,
    report_global_advance boolean,
    max_value numeric(19,2)
);


ALTER TABLE advance_assignment_template OWNER TO libreplan;

--
-- TOC entry 200 (class 1259 OID 1366680)
-- Name: advance_measurement; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE advance_measurement (
    id bigint NOT NULL,
    version bigint NOT NULL,
    date date,
    value numeric(19,2),
    advance_assignment_id bigint,
    communication_date timestamp without time zone
);


ALTER TABLE advance_measurement OWNER TO libreplan;

--
-- TOC entry 201 (class 1259 OID 1366685)
-- Name: advance_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE advance_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    unit_name character varying(255),
    default_max_value numeric(19,4),
    updatable boolean,
    unit_precision numeric(19,4),
    active boolean,
    percentage boolean,
    quality_form boolean,
    read_only boolean DEFAULT false NOT NULL
);


ALTER TABLE advance_type OWNER TO libreplan;

--
-- TOC entry 202 (class 1259 OID 1366690)
-- Name: all_criterions; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE all_criterions (
    generic_resource_allocation_id bigint NOT NULL,
    criterion_id bigint NOT NULL
);


ALTER TABLE all_criterions OWNER TO libreplan;

--
-- TOC entry 203 (class 1259 OID 1366693)
-- Name: assignment_function; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE assignment_function (
    id bigint NOT NULL,
    version bigint NOT NULL
);


ALTER TABLE assignment_function OWNER TO libreplan;

--
-- TOC entry 204 (class 1259 OID 1366698)
-- Name: base_calendar; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE base_calendar (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    code_autogenerated boolean,
    last_sequence_code integer
);


ALTER TABLE base_calendar OWNER TO libreplan;

--
-- TOC entry 205 (class 1259 OID 1366706)
-- Name: calendar_availability; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE calendar_availability (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    start_date date,
    end_date date,
    base_calendar_id bigint,
    position_in_calendar integer
);


ALTER TABLE calendar_availability OWNER TO libreplan;

--
-- TOC entry 206 (class 1259 OID 1366711)
-- Name: calendar_data; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE calendar_data (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    parent bigint,
    expiring_date date,
    base_calendar_id bigint,
    position_in_calendar integer
);


ALTER TABLE calendar_data OWNER TO libreplan;

--
-- TOC entry 207 (class 1259 OID 1366716)
-- Name: calendar_exception; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE calendar_exception (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    date date,
    standard_effort integer,
    calendar_exception_id bigint,
    base_calendar_id bigint,
    allowed_extra_effort integer
);


ALTER TABLE calendar_exception OWNER TO libreplan;

--
-- TOC entry 208 (class 1259 OID 1366721)
-- Name: calendar_exception_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE calendar_exception_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    code_autogenerated boolean NOT NULL,
    name character varying(255),
    color character varying(255),
    standard_effort integer,
    allowed_extra_effort integer,
    updatable boolean DEFAULT true NOT NULL
);


ALTER TABLE calendar_exception_type OWNER TO libreplan;

--
-- TOC entry 224 (class 1259 OID 1366815)
-- Name: capacity_per_day; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE capacity_per_day (
    base_calendar_id bigint NOT NULL,
    standard_effort integer,
    day_id integer NOT NULL,
    allowed_extra_effort integer
);


ALTER TABLE capacity_per_day OWNER TO libreplan;

--
-- TOC entry 209 (class 1259 OID 1366729)
-- Name: configuration; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE configuration (
    id bigint NOT NULL,
    version bigint NOT NULL,
    configuration_id bigint,
    company_code character varying(255),
    generate_code_for_cost_category boolean NOT NULL,
    generate_code_for_calendar_exception_type boolean NOT NULL,
    generate_code_for_work_report_type boolean NOT NULL,
    generate_code_for_criterion boolean NOT NULL,
    generate_code_for_label boolean NOT NULL,
    generate_code_for_work_report boolean NOT NULL,
    generate_code_for_resources boolean NOT NULL,
    generate_code_for_types_of_work_hours boolean NOT NULL,
    generate_code_for_material_categories boolean NOT NULL,
    generate_code_for_unit_types boolean NOT NULL,
    generate_code_for_base_calendars boolean NOT NULL,
    monte_carlo_method_tab_visible boolean NOT NULL,
    progress_type integer,
    company_logo_url character varying(255),
    scenarios_visible boolean,
    changed_default_admin_password boolean DEFAULT false NOT NULL,
    changed_default_wsreader_password boolean DEFAULT false NOT NULL,
    changed_default_wswriter_password boolean DEFAULT false NOT NULL,
    ldap_host character varying(255),
    ldap_port character varying(5),
    ldap_base character varying(255),
    ldap_userdn character varying(255),
    ldap_password character varying(255),
    ldap_userid character varying(255),
    ldap_save_password_db boolean DEFAULT true NOT NULL,
    ldap_auth_enabled boolean DEFAULT false NOT NULL,
    ldap_save_roles_db boolean DEFAULT false NOT NULL,
    ldap_group_path character varying(255),
    ldap_role_property character varying(255),
    ldap_search_query character varying(255),
    enabled_autocomplete_login boolean DEFAULT true NOT NULL,
    ldap_group_strategy boolean DEFAULT true NOT NULL,
    check_new_version_enabled boolean DEFAULT true NOT NULL,
    allow_to_gather_usage_stats_enabled boolean DEFAULT true NOT NULL,
    generate_code_for_expense_sheets boolean DEFAULT true NOT NULL,
    currency_code character varying(255) DEFAULT 'EUR'::character varying NOT NULL,
    currency_symbol character varying(255) DEFAULT '€'::character varying NOT NULL,
    personal_timesheets_type_of_work_hours bigint,
    changed_default_wssubcontracting_password boolean DEFAULT false NOT NULL,
    changed_default_manager_password boolean DEFAULT false NOT NULL,
    changed_default_hresources_password boolean DEFAULT false NOT NULL,
    changed_default_outsourcing_password boolean DEFAULT false NOT NULL,
    changed_default_reports_password boolean DEFAULT false NOT NULL,
    personal_timesheets_periodicity integer,
    max_users integer,
    max_resources integer,
    seconds_planning_warning integer NOT NULL,
    automatic_budget_enabled boolean DEFAULT false NOT NULL,
    automatic_budget_type_of_work_hours bigint,
    repository_location character varying(1024)
);


ALTER TABLE configuration OWNER TO libreplan;

--
-- TOC entry 302 (class 1259 OID 1368209)
-- Name: configuration_roles_ldap; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE configuration_roles_ldap (
    role_libreplan character varying(255) NOT NULL,
    role_ldap character varying(255) NOT NULL,
    id_configuration bigint NOT NULL
);


ALTER TABLE configuration_roles_ldap OWNER TO libreplan;

--
-- TOC entry 315 (class 1259 OID 1368404)
-- Name: connector; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE connector (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE connector OWNER TO libreplan;

--
-- TOC entry 314 (class 1259 OID 1368402)
-- Name: connector_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE connector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE connector_id_seq OWNER TO libreplan;

--
-- TOC entry 4165 (class 0 OID 0)
-- Dependencies: 314
-- Name: connector_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE connector_id_seq OWNED BY connector.id;


--
-- TOC entry 316 (class 1259 OID 1368410)
-- Name: connector_property; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE connector_property (
    connector_id bigint NOT NULL,
    connector_property_position integer NOT NULL,
    property_key character varying(255) NOT NULL,
    property_value character varying(255)
);


ALTER TABLE connector_property OWNER TO libreplan;

--
-- TOC entry 210 (class 1259 OID 1366734)
-- Name: consolidated_value; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE consolidated_value (
    id bigint NOT NULL,
    consolidated_value_type character varying(255) NOT NULL,
    version bigint NOT NULL,
    date date,
    value numeric(19,2),
    task_end_date date,
    consolidation_id bigint,
    advance_measurement_id bigint,
    task_end_date_effort_duration integer DEFAULT 0
);


ALTER TABLE consolidated_value OWNER TO libreplan;

--
-- TOC entry 211 (class 1259 OID 1366739)
-- Name: consolidation; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE consolidation (
    id bigint NOT NULL,
    consolidation_type character varying(255) NOT NULL,
    version bigint NOT NULL,
    dir_advance_assignment_id bigint,
    ind_advance_assignment_id bigint
);


ALTER TABLE consolidation OWNER TO libreplan;

--
-- TOC entry 212 (class 1259 OID 1366744)
-- Name: cost_category; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE cost_category (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    code_autogenerated boolean NOT NULL,
    last_hour_cost_sequence_code integer NOT NULL,
    enabled boolean
);


ALTER TABLE cost_category OWNER TO libreplan;

--
-- TOC entry 213 (class 1259 OID 1366752)
-- Name: criterion; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE criterion (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    predefined_criterion_internal_name character varying(255),
    active boolean,
    id_criterion_type bigint NOT NULL,
    parent bigint,
    id_cost_category bigint
);


ALTER TABLE criterion OWNER TO libreplan;

--
-- TOC entry 214 (class 1259 OID 1366760)
-- Name: criterion_requirement; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE criterion_requirement (
    id bigint NOT NULL,
    criterion_requirement_type character varying(255) NOT NULL,
    version bigint NOT NULL,
    hours_group_id bigint,
    order_element_id bigint,
    order_element_template_id bigint,
    criterion_id bigint,
    parent bigint,
    valid boolean
);


ALTER TABLE criterion_requirement OWNER TO libreplan;

--
-- TOC entry 215 (class 1259 OID 1366765)
-- Name: criterion_satisfaction; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE criterion_satisfaction (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    start_date date NOT NULL,
    finish_date date,
    is_deleted boolean,
    criterion bigint NOT NULL,
    resource bigint NOT NULL
);


ALTER TABLE criterion_satisfaction OWNER TO libreplan;

--
-- TOC entry 216 (class 1259 OID 1366770)
-- Name: criterion_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE criterion_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    predefined_type_internal_name character varying(255),
    description character varying(255),
    allow_simultaneous_criterions_per_resource boolean,
    allow_hierarchy boolean,
    last_criterion_sequence_code integer,
    enabled boolean,
    code_autogenerated boolean NOT NULL,
    resource integer
);


ALTER TABLE criterion_type OWNER TO libreplan;

--
-- TOC entry 304 (class 1259 OID 1368256)
-- Name: customer_communication; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE customer_communication (
    id bigint NOT NULL,
    version bigint NOT NULL,
    deadline timestamp without time zone,
    communication_type integer,
    communication_date timestamp without time zone,
    reviewed boolean,
    order_id bigint
);


ALTER TABLE customer_communication OWNER TO libreplan;

--
-- TOC entry 197 (class 1259 OID 1366664)
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE databasechangelog OWNER TO libreplan;

--
-- TOC entry 196 (class 1259 OID 1366659)
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE databasechangeloglock OWNER TO libreplan;

--
-- TOC entry 217 (class 1259 OID 1366778)
-- Name: day_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE day_assignment (
    id bigint NOT NULL,
    day_assignment_type character varying(255) NOT NULL,
    version bigint NOT NULL,
    duration integer NOT NULL,
    consolidated boolean,
    day date NOT NULL,
    resource_id bigint NOT NULL,
    specific_container_id bigint,
    generic_container_id bigint,
    derived_container_id bigint
);


ALTER TABLE day_assignment OWNER TO libreplan;

--
-- TOC entry 307 (class 1259 OID 1368269)
-- Name: deadline_communication; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE deadline_communication (
    id bigint NOT NULL,
    version bigint NOT NULL,
    save_date timestamp without time zone,
    deliver_date timestamp without time zone,
    order_id bigint
);


ALTER TABLE deadline_communication OWNER TO libreplan;

--
-- TOC entry 218 (class 1259 OID 1366783)
-- Name: dependency; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE dependency (
    id bigint NOT NULL,
    version bigint NOT NULL,
    origin bigint,
    destination bigint,
    queue_dependency bigint,
    type integer
);


ALTER TABLE dependency OWNER TO libreplan;

--
-- TOC entry 219 (class 1259 OID 1366788)
-- Name: derived_allocation; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE derived_allocation (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resource_allocation_id bigint,
    configurationunit bigint NOT NULL
);


ALTER TABLE derived_allocation OWNER TO libreplan;

--
-- TOC entry 220 (class 1259 OID 1366793)
-- Name: derived_day_assignments_container; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE derived_day_assignments_container (
    id bigint NOT NULL,
    version bigint NOT NULL,
    derived_allocation_id bigint,
    scenario bigint
);


ALTER TABLE derived_day_assignments_container OWNER TO libreplan;

--
-- TOC entry 221 (class 1259 OID 1366798)
-- Name: description_values; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE description_values (
    description_value_id bigint NOT NULL,
    fieldname character varying(255),
    value character varying(255)
);


ALTER TABLE description_values OWNER TO libreplan;

--
-- TOC entry 222 (class 1259 OID 1366804)
-- Name: description_values_in_line; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE description_values_in_line (
    description_value_id bigint NOT NULL,
    field_name character varying(255),
    value character varying(255)
);


ALTER TABLE description_values_in_line OWNER TO libreplan;

--
-- TOC entry 223 (class 1259 OID 1366810)
-- Name: direct_advance_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE direct_advance_assignment (
    advance_assignment_id bigint NOT NULL,
    direct_order_element_id bigint,
    max_value numeric(19,2)
);


ALTER TABLE direct_advance_assignment OWNER TO libreplan;

--
-- TOC entry 321 (class 1259 OID 1368471)
-- Name: email_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE email_template (
    id bigint NOT NULL,
    type integer,
    language integer,
    content character varying(2048),
    subject character varying(1024)
);


ALTER TABLE email_template OWNER TO libreplan;

--
-- TOC entry 320 (class 1259 OID 1368469)
-- Name: email_template_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE email_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE email_template_id_seq OWNER TO libreplan;

--
-- TOC entry 4166 (class 0 OID 0)
-- Dependencies: 320
-- Name: email_template_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE email_template_id_seq OWNED BY email_template.id;


--
-- TOC entry 309 (class 1259 OID 1368282)
-- Name: end_date_communication; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE end_date_communication (
    id bigint NOT NULL,
    version bigint NOT NULL,
    save_date timestamp without time zone,
    end_date timestamp without time zone,
    communication_date timestamp without time zone,
    order_id bigint,
    subcontracted_task_data_id bigint
);


ALTER TABLE end_date_communication OWNER TO libreplan;

--
-- TOC entry 225 (class 1259 OID 1366818)
-- Name: entity_sequence; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE entity_sequence (
    id bigint NOT NULL,
    version bigint NOT NULL,
    entity_name integer,
    prefix character varying(255),
    last_value integer,
    number_of_digits integer,
    active boolean
);


ALTER TABLE entity_sequence OWNER TO libreplan;

--
-- TOC entry 310 (class 1259 OID 1368295)
-- Name: expense_sheet; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE expense_sheet (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    code_autogenerated boolean,
    first_expense date,
    last_expense date,
    total numeric(19,2),
    description text,
    last_expense_sheet_line_sequence_code integer,
    personal boolean DEFAULT false NOT NULL
);


ALTER TABLE expense_sheet OWNER TO libreplan;

--
-- TOC entry 311 (class 1259 OID 1368303)
-- Name: expense_sheet_line; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE expense_sheet_line (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    value numeric(19,2),
    concept character varying(255),
    date date,
    order_element_id bigint,
    resource_id bigint,
    expense_sheet_id bigint
);


ALTER TABLE expense_sheet_line OWNER TO libreplan;

--
-- TOC entry 226 (class 1259 OID 1366823)
-- Name: external_company; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE external_company (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    nif character varying(255),
    client boolean,
    subcontractor boolean,
    interacts_with_applications boolean,
    app_uri character varying(255),
    our_company_login character varying(255),
    our_company_password character varying(255),
    company_user bigint
);


ALTER TABLE external_company OWNER TO libreplan;

--
-- TOC entry 329 (class 1259 OID 1368542)
-- Name: files; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE files (
    id bigint NOT NULL,
    name character varying(1024),
    type character varying(22),
    date timestamp without time zone,
    uploader bigint,
    parent bigint
);


ALTER TABLE files OWNER TO libreplan;

--
-- TOC entry 328 (class 1259 OID 1368540)
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE files_id_seq OWNER TO libreplan;

--
-- TOC entry 4167 (class 0 OID 0)
-- Dependencies: 328
-- Name: files_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE files_id_seq OWNED BY files.id;


--
-- TOC entry 227 (class 1259 OID 1366831)
-- Name: generic_day_assignments_container; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE generic_day_assignments_container (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resource_allocation_id bigint,
    scenario bigint,
    start_date date,
    duration_start_in_first_day integer,
    end_date date,
    duration_in_last_day integer
);


ALTER TABLE generic_day_assignments_container OWNER TO libreplan;

--
-- TOC entry 228 (class 1259 OID 1366836)
-- Name: generic_resource_allocation; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE generic_resource_allocation (
    resource_allocation_id bigint NOT NULL,
    resource_type integer
);


ALTER TABLE generic_resource_allocation OWNER TO libreplan;

--
-- TOC entry 229 (class 1259 OID 1366841)
-- Name: heading_field; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE heading_field (
    heading_id bigint NOT NULL,
    fieldname character varying(255),
    length integer,
    positionnumber integer
);


ALTER TABLE heading_field OWNER TO libreplan;

--
-- TOC entry 301 (class 1259 OID 1368125)
-- Name: hibernate_unique_key; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE hibernate_unique_key (
    next_hi integer
);


ALTER TABLE hibernate_unique_key OWNER TO libreplan;

--
-- TOC entry 230 (class 1259 OID 1366844)
-- Name: hour_cost; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE hour_cost (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    price_cost numeric(19,2),
    init_date date,
    end_date date,
    type_of_work_hours_id bigint,
    cost_category_id bigint
);


ALTER TABLE hour_cost OWNER TO libreplan;

--
-- TOC entry 231 (class 1259 OID 1366849)
-- Name: hours_group; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE hours_group (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    resource_type character varying(255),
    working_hours integer NOT NULL,
    percentage numeric(19,2),
    fixed_percentage boolean,
    parent_order_line bigint,
    order_line_template bigint
);


ALTER TABLE hours_group OWNER TO libreplan;

--
-- TOC entry 232 (class 1259 OID 1366857)
-- Name: indirect_advance_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE indirect_advance_assignment (
    advance_assignment_id bigint NOT NULL,
    indirect_order_element_id bigint
);


ALTER TABLE indirect_advance_assignment OWNER TO libreplan;

--
-- TOC entry 325 (class 1259 OID 1368496)
-- Name: issue_log; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE issue_log (
    id bigint NOT NULL,
    code character varying(25),
    project bigint,
    type integer,
    description character varying(1024),
    priority integer,
    severity integer,
    created_by bigint,
    assigned_to character varying(512),
    status character varying(50),
    date_raised timestamp without time zone,
    deadline timestamp without time zone,
    date_resolved timestamp without time zone,
    notes character varying(1024)
);


ALTER TABLE issue_log OWNER TO libreplan;

--
-- TOC entry 324 (class 1259 OID 1368494)
-- Name: issue_log_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE issue_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE issue_log_id_seq OWNER TO libreplan;

--
-- TOC entry 4168 (class 0 OID 0)
-- Dependencies: 324
-- Name: issue_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE issue_log_id_seq OWNED BY issue_log.id;


--
-- TOC entry 318 (class 1259 OID 1368425)
-- Name: job_scheduler_configuration; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE job_scheduler_configuration (
    id bigint NOT NULL,
    version bigint NOT NULL,
    job_group character varying(255) NOT NULL,
    job_name character varying(255) NOT NULL,
    cron_expression character varying(255) NOT NULL,
    job_class_name integer NOT NULL,
    connector_name character varying(255),
    schedule boolean
);


ALTER TABLE job_scheduler_configuration OWNER TO libreplan;

--
-- TOC entry 317 (class 1259 OID 1368423)
-- Name: job_scheduler_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE job_scheduler_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE job_scheduler_configuration_id_seq OWNER TO libreplan;

--
-- TOC entry 4169 (class 0 OID 0)
-- Dependencies: 317
-- Name: job_scheduler_configuration_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE job_scheduler_configuration_id_seq OWNED BY job_scheduler_configuration.id;


--
-- TOC entry 233 (class 1259 OID 1366862)
-- Name: label; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE label (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    label_type_id bigint
);


ALTER TABLE label OWNER TO libreplan;

--
-- TOC entry 234 (class 1259 OID 1366870)
-- Name: label_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE label_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    code_autogenerated boolean NOT NULL,
    last_label_sequence_code integer
);


ALTER TABLE label_type OWNER TO libreplan;

--
-- TOC entry 235 (class 1259 OID 1366878)
-- Name: limiting_resource_queue; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE limiting_resource_queue (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resource_id bigint
);


ALTER TABLE limiting_resource_queue OWNER TO libreplan;

--
-- TOC entry 236 (class 1259 OID 1366883)
-- Name: limiting_resource_queue_dependency; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE limiting_resource_queue_dependency (
    id bigint NOT NULL,
    type integer,
    origin_queue_element_id bigint,
    destiny_queue_element_id bigint
);


ALTER TABLE limiting_resource_queue_dependency OWNER TO libreplan;

--
-- TOC entry 237 (class 1259 OID 1366888)
-- Name: limiting_resource_queue_element; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE limiting_resource_queue_element (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resource_allocation_id bigint,
    limiting_resource_queue_id bigint,
    earlier_start_date_because_of_gantt timestamp without time zone,
    earliest_end_date_because_of_gantt timestamp without time zone,
    creation_timestamp bigint,
    start_date date,
    start_hour integer,
    end_date date,
    end_hour integer
);


ALTER TABLE limiting_resource_queue_element OWNER TO libreplan;

--
-- TOC entry 319 (class 1259 OID 1368457)
-- Name: limits; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE limits (
    type character varying(20),
    value integer,
    id bigint NOT NULL
);


ALTER TABLE limits OWNER TO libreplan;

--
-- TOC entry 238 (class 1259 OID 1366893)
-- Name: line_field; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE line_field (
    heading_id bigint NOT NULL,
    fieldname character varying(255),
    length integer,
    positionnumber integer
);


ALTER TABLE line_field OWNER TO libreplan;

--
-- TOC entry 239 (class 1259 OID 1366896)
-- Name: machine; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE machine (
    machine_id bigint NOT NULL,
    name character varying(255),
    description character varying(255)
);


ALTER TABLE machine OWNER TO libreplan;

--
-- TOC entry 240 (class 1259 OID 1366904)
-- Name: machine_configuration_unit_required_criterions; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE machine_configuration_unit_required_criterions (
    id bigint NOT NULL,
    criterion_id bigint NOT NULL
);


ALTER TABLE machine_configuration_unit_required_criterions OWNER TO libreplan;

--
-- TOC entry 241 (class 1259 OID 1366907)
-- Name: machine_worker_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE machine_worker_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    start_date timestamp without time zone,
    finish_date timestamp without time zone,
    configuration_id bigint NOT NULL,
    worker_id bigint
);


ALTER TABLE machine_worker_assignment OWNER TO libreplan;

--
-- TOC entry 242 (class 1259 OID 1366912)
-- Name: machine_workers_configuration_unit; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE machine_workers_configuration_unit (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255) NOT NULL,
    alpha numeric(19,2) NOT NULL,
    machine bigint NOT NULL
);


ALTER TABLE machine_workers_configuration_unit OWNER TO libreplan;

--
-- TOC entry 303 (class 1259 OID 1368235)
-- Name: manual_function; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE manual_function (
    assignment_function_id bigint NOT NULL
);


ALTER TABLE manual_function OWNER TO libreplan;

--
-- TOC entry 243 (class 1259 OID 1366917)
-- Name: material; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE material (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255),
    default_unit_price numeric(19,2),
    unit_type bigint,
    disabled boolean,
    category_id bigint
);


ALTER TABLE material OWNER TO libreplan;

--
-- TOC entry 244 (class 1259 OID 1366925)
-- Name: material_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE material_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    units numeric(19,2),
    unit_price numeric(19,2),
    material_id bigint,
    estimated_availability timestamp without time zone,
    status integer,
    order_element_id bigint
);


ALTER TABLE material_assignment OWNER TO libreplan;

--
-- TOC entry 245 (class 1259 OID 1366930)
-- Name: material_assignment_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE material_assignment_template (
    id bigint NOT NULL,
    version bigint NOT NULL,
    units numeric(19,2),
    unit_price numeric(19,2),
    material_id bigint,
    order_element_template_id bigint
);


ALTER TABLE material_assignment_template OWNER TO libreplan;

--
-- TOC entry 246 (class 1259 OID 1366935)
-- Name: material_category; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE material_category (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    code_autogenerated boolean NOT NULL,
    last_material_sequence_code integer NOT NULL,
    parent_id bigint
);


ALTER TABLE material_category OWNER TO libreplan;

--
-- TOC entry 323 (class 1259 OID 1368486)
-- Name: notification_queue; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE notification_queue (
    id bigint NOT NULL,
    type integer,
    updated timestamp without time zone,
    resource bigint,
    task bigint,
    project bigint
);


ALTER TABLE notification_queue OWNER TO libreplan;

--
-- TOC entry 322 (class 1259 OID 1368484)
-- Name: notification_queue_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE notification_queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE notification_queue_id_seq OWNER TO libreplan;

--
-- TOC entry 4170 (class 0 OID 0)
-- Dependencies: 322
-- Name: notification_queue_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE notification_queue_id_seq OWNED BY notification_queue.id;


--
-- TOC entry 247 (class 1259 OID 1366943)
-- Name: order_authorization; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_authorization (
    id bigint NOT NULL,
    order_authorization_subclass character varying(255) NOT NULL,
    version bigint NOT NULL,
    authorization_type character varying(255) NOT NULL,
    order_id bigint,
    user_id bigint,
    profile_id bigint
);


ALTER TABLE order_authorization OWNER TO libreplan;

--
-- TOC entry 248 (class 1259 OID 1366951)
-- Name: order_element; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_element (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    description text,
    code character varying(255),
    init_date timestamp without time zone,
    deadline timestamp without time zone,
    last_advance_measurement_for_spreading numeric(19,2),
    dirty_last_advance_measurement_for_spreading boolean,
    parent bigint,
    template bigint,
    external_code character varying(255),
    position_in_container integer
);


ALTER TABLE order_element OWNER TO libreplan;

--
-- TOC entry 249 (class 1259 OID 1366959)
-- Name: order_element_label; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_element_label (
    order_element_id bigint NOT NULL,
    label_id bigint NOT NULL
);


ALTER TABLE order_element_label OWNER TO libreplan;

--
-- TOC entry 250 (class 1259 OID 1366962)
-- Name: order_element_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_element_template (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    description text,
    start_as_days_from_beginning integer,
    deadline_as_days_from_beginning integer,
    scheduling_state_type integer,
    parent bigint,
    position_in_container integer
);


ALTER TABLE order_element_template OWNER TO libreplan;

--
-- TOC entry 251 (class 1259 OID 1366970)
-- Name: order_element_template_label; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_element_template_label (
    order_element_template_id bigint NOT NULL,
    label_id bigint NOT NULL
);


ALTER TABLE order_element_template_label OWNER TO libreplan;

--
-- TOC entry 252 (class 1259 OID 1366973)
-- Name: order_element_template_quality_form; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_element_template_quality_form (
    order_element_template_id bigint NOT NULL,
    quality_form_id bigint NOT NULL
);


ALTER TABLE order_element_template_quality_form OWNER TO libreplan;

--
-- TOC entry 253 (class 1259 OID 1366976)
-- Name: order_line; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_line (
    order_element_id bigint NOT NULL,
    last_hours_group_sequence_code integer,
    budget numeric(19,2) DEFAULT 0 NOT NULL
);


ALTER TABLE order_line OWNER TO libreplan;

--
-- TOC entry 254 (class 1259 OID 1366981)
-- Name: order_line_group; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_line_group (
    order_element_id bigint NOT NULL
);


ALTER TABLE order_line_group OWNER TO libreplan;

--
-- TOC entry 255 (class 1259 OID 1366986)
-- Name: order_line_group_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_line_group_template (
    group_template_id bigint NOT NULL
);


ALTER TABLE order_line_group_template OWNER TO libreplan;

--
-- TOC entry 256 (class 1259 OID 1366991)
-- Name: order_line_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_line_template (
    order_line_template_id bigint NOT NULL,
    last_hours_group_sequence_code integer,
    budget numeric(19,2) DEFAULT 0 NOT NULL
);


ALTER TABLE order_line_template OWNER TO libreplan;

--
-- TOC entry 313 (class 1259 OID 1368389)
-- Name: order_sync_info; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_sync_info (
    id bigint NOT NULL,
    version bigint NOT NULL,
    last_sync_date timestamp without time zone NOT NULL,
    key character varying(255) NOT NULL,
    connector_name character varying(255) NOT NULL,
    order_element_id bigint
);


ALTER TABLE order_sync_info OWNER TO libreplan;

--
-- TOC entry 257 (class 1259 OID 1366996)
-- Name: order_table; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_table (
    order_element_id bigint NOT NULL,
    responsible character varying(255),
    dependencies_constraints_have_priority boolean,
    code_autogenerated boolean,
    last_order_element_sequence_code integer,
    work_budget numeric(19,2),
    materials_budget numeric(19,2),
    total_hours integer,
    customer_reference character varying(255),
    external_code character varying(255),
    state integer,
    customer bigint,
    base_calendar_id bigint,
    scheduling_mode integer,
    hours_margin integer,
    budget_margin integer
);


ALTER TABLE order_table OWNER TO libreplan;

--
-- TOC entry 258 (class 1259 OID 1367004)
-- Name: order_template; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_template (
    order_template_id bigint NOT NULL,
    base_calendar_id bigint
);


ALTER TABLE order_template OWNER TO libreplan;

--
-- TOC entry 259 (class 1259 OID 1367009)
-- Name: order_version; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE order_version (
    id bigint NOT NULL,
    version bigint NOT NULL,
    modification_by_owner_timestamp timestamp without time zone,
    ownerscenario bigint
);


ALTER TABLE order_version OWNER TO libreplan;

--
-- TOC entry 260 (class 1259 OID 1367014)
-- Name: planning_data; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE planning_data (
    planning_data_id bigint NOT NULL,
    progress_by_duration numeric(19,6),
    progress_by_num_hours numeric(19,6),
    progress_all_by_num_hours numeric(19,6),
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE planning_data OWNER TO libreplan;

--
-- TOC entry 261 (class 1259 OID 1367019)
-- Name: profile_roles; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE profile_roles (
    profile_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE profile_roles OWNER TO libreplan;

--
-- TOC entry 262 (class 1259 OID 1367022)
-- Name: profile_table; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE profile_table (
    id bigint NOT NULL,
    version bigint NOT NULL,
    profile_name character varying(255) NOT NULL
);


ALTER TABLE profile_table OWNER TO libreplan;

--
-- TOC entry 263 (class 1259 OID 1367027)
-- Name: quality_form; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE quality_form (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    description character varying(255),
    quality_form_type integer,
    report_advance boolean,
    advance_type_id bigint
);


ALTER TABLE quality_form OWNER TO libreplan;

--
-- TOC entry 264 (class 1259 OID 1367035)
-- Name: quality_form_items; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE quality_form_items (
    quality_form_id bigint NOT NULL,
    name character varying(255),
    percentage numeric(19,2),
    "position" integer,
    idx integer NOT NULL
);


ALTER TABLE quality_form_items OWNER TO libreplan;

--
-- TOC entry 265 (class 1259 OID 1367038)
-- Name: resource; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE resource (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    code_autogenerated boolean NOT NULL,
    base_calendar_id bigint,
    resource_type character varying(64) NOT NULL
);


ALTER TABLE resource OWNER TO libreplan;

--
-- TOC entry 266 (class 1259 OID 1367043)
-- Name: resource_allocation; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE resource_allocation (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resources_per_day numeric(19,2),
    intended_total_hours integer,
    task bigint,
    assignment_function bigint,
    intended_resources_per_day numeric(19,2),
    intended_total_assignment integer DEFAULT 0,
    intended_non_consolidated_effort integer DEFAULT 0
);


ALTER TABLE resource_allocation OWNER TO libreplan;

--
-- TOC entry 267 (class 1259 OID 1367048)
-- Name: resource_calendar; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE resource_calendar (
    base_calendar_id bigint NOT NULL,
    capacity integer NOT NULL
);


ALTER TABLE resource_calendar OWNER TO libreplan;

--
-- TOC entry 268 (class 1259 OID 1367053)
-- Name: resources_cost_category_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE resources_cost_category_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    init_date date,
    end_date date,
    cost_category_id bigint,
    resource_id bigint
);


ALTER TABLE resources_cost_category_assignment OWNER TO libreplan;

--
-- TOC entry 327 (class 1259 OID 1368519)
-- Name: risk_log; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE risk_log (
    id bigint NOT NULL,
    code character varying(25),
    project bigint,
    description character varying(1024),
    probability integer,
    impact integer,
    score integer,
    created_by bigint,
    responsible character varying(512),
    status character varying(512),
    contingency character varying(1024),
    counter_measures character varying(1024),
    action_when timestamp without time zone,
    date_created timestamp without time zone,
    notes character varying(1024)
);


ALTER TABLE risk_log OWNER TO libreplan;

--
-- TOC entry 326 (class 1259 OID 1368517)
-- Name: risk_log_id_seq; Type: SEQUENCE; Schema: public; Owner: libreplan
--

CREATE SEQUENCE risk_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE risk_log_id_seq OWNER TO libreplan;

--
-- TOC entry 4171 (class 0 OID 0)
-- Dependencies: 326
-- Name: risk_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: libreplan
--

ALTER SEQUENCE risk_log_id_seq OWNED BY risk_log.id;


--
-- TOC entry 269 (class 1259 OID 1367058)
-- Name: roles_table; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE roles_table (
    user_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE roles_table OWNER TO libreplan;

--
-- TOC entry 270 (class 1259 OID 1367061)
-- Name: scenario; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE scenario (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    description character varying(255),
    last_not_owned_reassignations_time_stamp timestamp without time zone,
    predecessor bigint
);


ALTER TABLE scenario OWNER TO libreplan;

--
-- TOC entry 271 (class 1259 OID 1367069)
-- Name: scenario_orders; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE scenario_orders (
    order_id bigint NOT NULL,
    order_version_id bigint NOT NULL,
    scenario_id bigint NOT NULL
);


ALTER TABLE scenario_orders OWNER TO libreplan;

--
-- TOC entry 272 (class 1259 OID 1367072)
-- Name: scheduling_data_for_version; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE scheduling_data_for_version (
    id bigint NOT NULL,
    version bigint NOT NULL,
    scheduling_state_type integer,
    order_element_id bigint
);


ALTER TABLE scheduling_data_for_version OWNER TO libreplan;

--
-- TOC entry 273 (class 1259 OID 1367077)
-- Name: scheduling_states_by_order_version; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE scheduling_states_by_order_version (
    order_element_id bigint NOT NULL,
    scheduling_state_for_version_id bigint NOT NULL,
    order_version_id bigint NOT NULL
);


ALTER TABLE scheduling_states_by_order_version OWNER TO libreplan;

--
-- TOC entry 274 (class 1259 OID 1367080)
-- Name: sigmoid_function; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE sigmoid_function (
    assignment_function_id bigint NOT NULL
);


ALTER TABLE sigmoid_function OWNER TO libreplan;

--
-- TOC entry 275 (class 1259 OID 1367085)
-- Name: specific_day_assignments_container; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE specific_day_assignments_container (
    id bigint NOT NULL,
    version bigint NOT NULL,
    resource_allocation_id bigint,
    scenario bigint,
    start_date date,
    duration_start_in_first_day integer,
    end_date date,
    duration_in_last_day integer
);


ALTER TABLE specific_day_assignments_container OWNER TO libreplan;

--
-- TOC entry 276 (class 1259 OID 1367090)
-- Name: specific_resource_allocation; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE specific_resource_allocation (
    resource_allocation_id bigint NOT NULL,
    resource bigint
);


ALTER TABLE specific_resource_allocation OWNER TO libreplan;

--
-- TOC entry 277 (class 1259 OID 1367095)
-- Name: stretches; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE stretches (
    assignment_function_id bigint NOT NULL,
    length_percentage numeric(19,2) NOT NULL,
    amount_work_percentage numeric(19,2) NOT NULL,
    stretch_position integer NOT NULL
);


ALTER TABLE stretches OWNER TO libreplan;

--
-- TOC entry 278 (class 1259 OID 1367098)
-- Name: stretches_function; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE stretches_function (
    assignment_function_id bigint NOT NULL,
    type integer
);


ALTER TABLE stretches_function OWNER TO libreplan;

--
-- TOC entry 279 (class 1259 OID 1367103)
-- Name: subcontracted_task_data; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE subcontracted_task_data (
    id bigint NOT NULL,
    version bigint NOT NULL,
    external_company bigint,
    subcontratation_date timestamp without time zone,
    subcontract_communication_date timestamp without time zone,
    work_description character varying(255),
    subcontract_price numeric(19,2),
    subcontracted_code character varying(255),
    node_without_children_exported boolean,
    labels_exported boolean,
    material_assignments_exported boolean,
    hours_groups_exported boolean,
    state integer
);


ALTER TABLE subcontracted_task_data OWNER TO libreplan;

--
-- TOC entry 305 (class 1259 OID 1368261)
-- Name: subcontractor_communication; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE subcontractor_communication (
    id bigint NOT NULL,
    version bigint NOT NULL,
    communication_type integer,
    communication_date timestamp without time zone,
    reviewed boolean,
    subcontracted_task_data bigint
);


ALTER TABLE subcontractor_communication OWNER TO libreplan;

--
-- TOC entry 306 (class 1259 OID 1368266)
-- Name: subcontractor_communication_values; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE subcontractor_communication_values (
    subcontractor_communication_id bigint NOT NULL,
    date timestamp without time zone,
    progress numeric(19,2),
    idx integer NOT NULL
);


ALTER TABLE subcontractor_communication_values OWNER TO libreplan;

--
-- TOC entry 308 (class 1259 OID 1368274)
-- Name: subcontractor_deliver_date; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE subcontractor_deliver_date (
    id bigint NOT NULL,
    version bigint NOT NULL,
    save_date timestamp without time zone,
    subcontractor_deliver_date timestamp without time zone,
    communication_date timestamp without time zone,
    subcontracted_task_data_id bigint
);


ALTER TABLE subcontractor_deliver_date OWNER TO libreplan;

--
-- TOC entry 280 (class 1259 OID 1367111)
-- Name: sum_charged_effort; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE sum_charged_effort (
    id bigint NOT NULL,
    version bigint NOT NULL,
    direct_charged_effort integer,
    indirect_charged_effort integer,
    order_element bigint,
    first_timesheet_date timestamp without time zone,
    last_timesheet_date timestamp without time zone,
    finished_timesheets boolean DEFAULT false NOT NULL
);


ALTER TABLE sum_charged_effort OWNER TO libreplan;

--
-- TOC entry 312 (class 1259 OID 1368348)
-- Name: sum_expenses; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE sum_expenses (
    id bigint NOT NULL,
    version bigint NOT NULL,
    order_element_id bigint,
    total_direct_expenses numeric(19,2),
    total_indirect_expenses numeric(19,2)
);


ALTER TABLE sum_expenses OWNER TO libreplan;

--
-- TOC entry 281 (class 1259 OID 1367116)
-- Name: task; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task (
    task_element_id bigint NOT NULL,
    calculated_value integer,
    constraint_type integer,
    constraint_date date,
    workable_days integer,
    allocation_direction integer,
    subcontracted_task_data_id bigint,
    priority integer,
    constraint_date_effort_duration integer DEFAULT 0
);


ALTER TABLE task OWNER TO libreplan;

--
-- TOC entry 282 (class 1259 OID 1367121)
-- Name: task_element; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_element (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    notes text,
    start_date date NOT NULL,
    start_day_duration integer,
    end_date date NOT NULL,
    end_day_duration integer,
    deadline date,
    advance_percentage numeric(19,4),
    sum_of_assigned_effort integer,
    parent bigint,
    base_calendar_id bigint,
    position_in_parent integer,
    updated_from_timesheets boolean DEFAULT false NOT NULL
);


ALTER TABLE task_element OWNER TO libreplan;

--
-- TOC entry 283 (class 1259 OID 1367129)
-- Name: task_group; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_group (
    task_element_id bigint NOT NULL
);


ALTER TABLE task_group OWNER TO libreplan;

--
-- TOC entry 284 (class 1259 OID 1367134)
-- Name: task_milestone; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_milestone (
    task_element_id bigint NOT NULL,
    constraint_type integer,
    constraint_date date,
    constraint_date_effort_duration integer DEFAULT 0
);


ALTER TABLE task_milestone OWNER TO libreplan;

--
-- TOC entry 285 (class 1259 OID 1367139)
-- Name: task_quality_form; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_quality_form (
    id bigint NOT NULL,
    version bigint NOT NULL,
    quality_form_id bigint,
    order_element_id bigint,
    report_advance boolean
);


ALTER TABLE task_quality_form OWNER TO libreplan;

--
-- TOC entry 286 (class 1259 OID 1367144)
-- Name: task_quality_form_items; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_quality_form_items (
    task_quality_form_id bigint NOT NULL,
    name character varying(255),
    percentage numeric(19,2),
    "position" integer,
    passed boolean,
    date timestamp without time zone,
    idx integer NOT NULL
);


ALTER TABLE task_quality_form_items OWNER TO libreplan;

--
-- TOC entry 287 (class 1259 OID 1367147)
-- Name: task_source; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_source (
    id bigint NOT NULL,
    version bigint NOT NULL,
    schedulingdata bigint
);


ALTER TABLE task_source OWNER TO libreplan;

--
-- TOC entry 288 (class 1259 OID 1367152)
-- Name: task_source_hours_groups; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE task_source_hours_groups (
    task_source_id bigint NOT NULL,
    hours_group_id bigint NOT NULL
);


ALTER TABLE task_source_hours_groups OWNER TO libreplan;

--
-- TOC entry 289 (class 1259 OID 1367155)
-- Name: type_of_work_hours; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE type_of_work_hours (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    code character varying(255),
    default_price numeric(19,2),
    enabled boolean,
    code_autogenerated boolean NOT NULL
);


ALTER TABLE type_of_work_hours OWNER TO libreplan;

--
-- TOC entry 290 (class 1259 OID 1367163)
-- Name: unit_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE unit_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    measure character varying(255),
    code_autogenerated boolean NOT NULL
);


ALTER TABLE unit_type OWNER TO libreplan;

--
-- TOC entry 291 (class 1259 OID 1367171)
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE user_profiles (
    user_id bigint NOT NULL,
    profile_id bigint NOT NULL
);


ALTER TABLE user_profiles OWNER TO libreplan;

--
-- TOC entry 292 (class 1259 OID 1367174)
-- Name: user_table; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE user_table (
    id bigint NOT NULL,
    version bigint NOT NULL,
    login_name character varying(255) NOT NULL,
    password character varying(255),
    email character varying(255),
    disabled boolean,
    lastconnectedscenario bigint,
    libreplan_user boolean DEFAULT true NOT NULL,
    application_language integer DEFAULT 0,
    expand_company_planning_view_charts boolean DEFAULT false NOT NULL,
    expand_order_planning_view_charts boolean DEFAULT true NOT NULL,
    expand_resource_load_view_charts boolean DEFAULT true NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    projects_filter_period_since integer,
    projects_filter_period_to integer,
    resources_load_filter_period_since integer,
    resources_load_filter_period_to integer,
    projects_filter_label_id bigint,
    resources_load_filter_criterion_id bigint,
    show_reported_hours_on boolean DEFAULT false NOT NULL,
    show_resources_on boolean DEFAULT false NOT NULL,
    show_advances_on boolean DEFAULT false NOT NULL,
    show_labels_on boolean DEFAULT false NOT NULL,
    show_money_cost_bar_on boolean DEFAULT false NOT NULL,
    projects_filter_finished_on boolean DEFAULT false NOT NULL
);


ALTER TABLE user_table OWNER TO libreplan;

--
-- TOC entry 293 (class 1259 OID 1367182)
-- Name: virtual_worker; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE virtual_worker (
    virtual_worker_id bigint NOT NULL,
    observations character varying(255)
);


ALTER TABLE virtual_worker OWNER TO libreplan;

--
-- TOC entry 294 (class 1259 OID 1367187)
-- Name: work_report; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE work_report (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    date timestamp without time zone,
    code_autogenerated boolean NOT NULL,
    last_work_report_line_sequence_code integer,
    ork_report_type_id bigint NOT NULL,
    resource_id bigint,
    order_element_id bigint
);


ALTER TABLE work_report OWNER TO libreplan;

--
-- TOC entry 295 (class 1259 OID 1367192)
-- Name: work_report_label_type_assignment; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE work_report_label_type_assignment (
    id bigint NOT NULL,
    version bigint NOT NULL,
    labels_shared_by_lines boolean,
    position_number integer,
    label_type_id bigint,
    label_id bigint,
    work_report_type_id bigint
);


ALTER TABLE work_report_label_type_assignment OWNER TO libreplan;

--
-- TOC entry 296 (class 1259 OID 1367197)
-- Name: work_report_line; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE work_report_line (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    effort integer,
    date timestamp without time zone,
    clock_start integer,
    clock_finish integer,
    work_report_id bigint,
    resource_id bigint NOT NULL,
    order_element_id bigint NOT NULL,
    type_work_hours_id bigint NOT NULL,
    finished boolean DEFAULT false NOT NULL
);


ALTER TABLE work_report_line OWNER TO libreplan;

--
-- TOC entry 297 (class 1259 OID 1367202)
-- Name: work_report_type; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE work_report_type (
    id bigint NOT NULL,
    version bigint NOT NULL,
    name character varying(255),
    code character varying(255),
    date_is_shared_by_lines boolean,
    resource_is_shared_in_lines boolean,
    order_element_is_shared_in_lines boolean,
    code_autogenerated boolean NOT NULL,
    hours_management integer
);


ALTER TABLE work_report_type OWNER TO libreplan;

--
-- TOC entry 298 (class 1259 OID 1367210)
-- Name: worker; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE worker (
    worker_id bigint NOT NULL,
    first_name character varying(255),
    surname character varying(255),
    nif character varying(255),
    user_id bigint
);


ALTER TABLE worker OWNER TO libreplan;

--
-- TOC entry 299 (class 1259 OID 1367218)
-- Name: workreports_labels; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE workreports_labels (
    work_report_id bigint NOT NULL,
    label_id bigint NOT NULL
);


ALTER TABLE workreports_labels OWNER TO libreplan;

--
-- TOC entry 300 (class 1259 OID 1367221)
-- Name: workreportslines_labels; Type: TABLE; Schema: public; Owner: libreplan
--

CREATE TABLE workreportslines_labels (
    work_report_line_id bigint NOT NULL,
    label_id bigint NOT NULL
);


ALTER TABLE workreportslines_labels OWNER TO libreplan;

--
-- TOC entry 3386 (class 2604 OID 1368407)
-- Name: connector id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY connector ALTER COLUMN id SET DEFAULT nextval('public.connector_id_seq'::regclass);


--
-- TOC entry 3388 (class 2604 OID 1368474)
-- Name: email_template id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY email_template ALTER COLUMN id SET DEFAULT nextval('public.email_template_id_seq'::regclass);


--
-- TOC entry 3392 (class 2604 OID 1368545)
-- Name: files id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY files ALTER COLUMN id SET DEFAULT nextval('public.files_id_seq'::regclass);


--
-- TOC entry 3390 (class 2604 OID 1368499)
-- Name: issue_log id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY issue_log ALTER COLUMN id SET DEFAULT nextval('public.issue_log_id_seq'::regclass);


--
-- TOC entry 3387 (class 2604 OID 1368428)
-- Name: job_scheduler_configuration id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY job_scheduler_configuration ALTER COLUMN id SET DEFAULT nextval('public.job_scheduler_configuration_id_seq'::regclass);


--
-- TOC entry 3389 (class 2604 OID 1368489)
-- Name: notification_queue id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY notification_queue ALTER COLUMN id SET DEFAULT nextval('public.notification_queue_id_seq'::regclass);


--
-- TOC entry 3391 (class 2604 OID 1368522)
-- Name: risk_log id; Type: DEFAULT; Schema: public; Owner: libreplan
--

ALTER TABLE ONLY risk_log ALTER COLUMN id SET DEFAULT nextval('public.risk_log_id_seq'::regclass);
